apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-deployment
  labels:
    app: mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          ports:
          - containerPort: 27017
          env: # mongodb username and password
          - name: MONGO_INITDB_ROOT_USERNAME # env variable
            valueFrom: # The value will be pulled from Secret
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-username
          - name: MONGO_INITDB_ROOT_PASSWORD # env variable
            valueFrom: # The value will be pulled from Secret
              secretKeyRef:
                name: mongodb-secret
                key: mongo-root-password



# NOTE:
# The secret is configured in the K8 itself, so that it will not be committed to the repository.
#
# Secret must be created before the deployment
#